name: Update Homebrew Formula

on:
  workflow_run:
    workflows: ["new_release"]
    types: 
      - completed
  workflow_dispatch:
    inputs:
      tagName:
        description: 'Tag Name for Homebrew Formula'
        required: true
        default: 'v0.0.5' 

jobs:
  update-homebrew-formula:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Main Repository
        uses: actions/checkout@v2

      - name: Download Release Archive
        run: |
          TAG_NAME="${{ github.event.inputs.tagName || github.ref_name }}"
          curl -L -o "acervus-${TAG_NAME}.tar.gz" "https://github.com/paribu/acervus-cli/archive/refs/tags/${TAG_NAME}.tar.gz"

      - name: Calculate SHA256
        run: sha256sum "acervus-${TAG_NAME}.tar.gz" > sha256.txt

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Checkout Homebrew Formula Repository
        uses: actions/checkout@v2
        with:
          repository: "paribu/homebrew-acervus"
          ssh-key: ${{ secrets.DEPLOY_KEY }}
          path: "homebrew-formula"

      - name: Update Homebrew Formula
        run: |
          TAG_NAME="${{ github.event.inputs.tagName || github.ref_name }}"
          SHA256=$(cat sha256.txt | awk '{ print $1 }')
          sed -i "s|url \".*\"|url \"https://github.com/paribu/acervus-cli/archive/refs/tags/${TAG_NAME}.tar.gz\"|g" homebrew-formula/Formula/acervus/acervus.rb
          sed -i "s|sha256 \".*\"|sha256 \"$SHA256\"|g" homebrew-formula/Formula/acervus/acervus.rb

      - name: Commit and Push Changes
        run: |
          cd homebrew-formula
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add Formula/acervus/acervus.rb
          git commit -m "Update Acervus formula to ${GITHUB_REF_NAME}"
          git push
