name: Update Homebrew Formula

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  update-homebrew-formula:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Main Repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.21"

      - name: Build and Calculate SHA256
        run: |
          go build -o acervus
          sha256sum acervus > sha256.txt

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Checkout Homebrew Formula Repository
        uses: actions/checkout@v2
        with:
          repository: "paribu/homebrew-acervus"
          ssh-key: ${{ secrets.DEPLOY_KEY }}
          path: "homebrew-formula"

      - name: Update Homebrew Formula
        run: |
          SHA256=$(cat sha256.txt | awk '{ print $1 }')
          sed -i "s|url \".*\"|url \"https://github.com/paribu/acervus-cli/archive/refs/tags/${GITHUB_REF_NAME}.tar.gz\"|g" homebrew-formula/Formula/acervus/acervus.rb
          sed -i "s|sha256 \".*\"|sha256 \"$SHA256\"|g" homebrew-formula/Formula/acervus/acervus.rb

      - name: Commit and Push Changes
        run: |
          cd homebrew-formula
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add Formula/acervus/acervus.rb
          git commit -m "Update Acervus formula to ${GITHUB_REF_NAME}"
          git push
